# Generated by Django 4.0.4 on 2022-05-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sentence_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('wiki_title', 'target_lang')},
        ),
    ]
